---
- name: Deploy Arch Linux System
  hosts: arch_linux
  become: yes
  vars_files:
    - group_vars/all.yaml

  roles:
    # - role: cp_configs_from_host_2_ansible
    # - role: base
    # - role: packages
    # - role: desktop
    - role: user_configs



